### ISSUE TITLE
The app doesn't work.

### ISSUE THREAD

**Issue by quadrupleslap** [sbhs-forkbombers/sbhs-timetable-android#18]
> So, the update came up, I installed the update, and then the logout button disappeared, and it kept getting stuck at the "something should happen soon' screen. A reinstall didn't fix anything, and made things worse. It stays on the login page of sbhstimetable-node now.

~ Shadman Habib - Year 10, Samsung Galaxy S2, CyanogenMod 12 (Android 5.0.2)

Please fix soon. Thanks.

**Comment by gnustomp** [comment]
User issue. Works for everyone else.

**Comment by quadrupleslap** [comment]
Please reopen :pray:. I can confirm that it doesn't work on my stock android Galaxy Note 10.1. Please post debugging instructions if that would help you.

**Comment by gnustomp** [comment]
Steps to reproduce?

**Comment by quadrupleslap** [comment]
All I did was update it. Although I had like android 4.2.something.
It never loads.

**Comment by gnustomp** [comment]
Clear data, uninstall, reinstall?

**Comment by gnustomp** [comment]
I'll add that there was a broken build published to Google Play. It's possible that staged rollouts meant you got that build instead of the one after it.

**Comment by quadrupleslap** [comment]
Do you even test? Also, yet another person has a broken install of sbhstimetable-android.

**Comment by gnustomp** [comment]
Direct blame about not testing to @keepcalm444.
Also a rewrite is happening, so hold your bugs tight, they'll be gone soon.

**Comment by gnustomp** [comment]
This bug isn't necessarily in this app, and may be an issue with -node instead.

**Comment by gnustomp** [comment]
It also appears to be fixed in the rewrite.

**Comment by quadrupleslap** [comment]
Why on earth is this linked to sbhstt-node :\

**Comment by gnustomp** [comment]
Something something custom APIs.

**Comment by keepcalm444** [comment]
My strategies for publishing builds should not be judged.
Also,
>rewrite
>bug-free
>uwotm8

**Comment by quadrupleslap** [comment]
If you have already published it, no, it still doesn't work.
Wow.

**Comment by quadrupleslap** [comment]
Doge is massif liar. Down with the establishment! Glory to the people! The shackles of memes shall hold us no longer!

**Comment by gnustomp** [comment]
Stop spamming email and IRC notifications.

**Comment by quadrupleslap** [comment]
??? i have no idea wat ur talking about
